In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train = pd.read_csv(r"C:\Users\Santanu Das\Desktop\titanic\train.csv")
test = pd.read_csv(r"C:\Users\Santanu Das\Desktop\titanic\test.csv")

In [3]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df = train.drop(['Name', 'Ticket', 'Cabin'], axis=1)
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [5]:
df.Sex[df.Sex == 'male'] = 1
df.Sex[df.Sex == 'female'] = 0
df.head()

C:\Users\Santanu Das\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Santanu Das\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

   PassengerId  Survived  Pclass Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3   1  22.0      1      0   7.2500        S
1            2         1       1   0  38.0      1      0  71.2833        C
2            3         1       3   0  26.0      0      0   7.9250        S
3            4         1       1   0  35.0      1      0  53.1000        S
4            5         0       3   1  35.0      0      0   8.0500        S

In [6]:
df1 = df.fillna(df[['Age']].mean(axis = 0))
df1

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,1,22.000000,1,0,7.2500,S
1,2,1,1,0,38.000000,1,0,71.2833,C
2,3,1,3,0,26.000000,0,0,7.9250,S
3,4,1,1,0,35.000000,1,0,53.1000,S
4,5,0,3,1,35.000000,0,0,8.0500,S
5,6,0,3,1,29.699118,0,0,8.4583,Q
6,7,0,1,1,54.000000,0,0,51.8625,S
7,8,0,3,1,2.000000,3,1,21.0750,S
8,9,1,3,0,27.000000,0,2,11.1333,S
9,10,1,2,0,14.000000,1,0,30.0708,C
10,11,1,3,0,4.000000,1,1,16.7000,S
11,12,1,1,0,58.000000,0,0,26.5500,S
12,13,0,3,1,20.000000,0,0,8.0500,S
13,14,0,3,1,39.000000,1,5,31.2750,S
14,15,0,3,0,14.000000,0,0,7.8542,S
15,16,1,2,0,55.000000,0,0,16.0000,S
16,17,0,3,1,2.000000,4,1,29.1250,Q
17,18,1,2,1,29.699118,0,0,13.0000,S
18,19,0,3,0,31.000000,1,0,18.0000,S
19,20,1,3,0,29.699118,0,0,7.2250,C
20,21,0,2,1,35.000000,0,0,26.0000,S
21,22,1,2,1,34.000000,0,0,13.0000,S
22,23,1,3,0,15.000000,0,0,8.0292,Q
23,24,1,1,1,28.000000,0,0,35.5000,S
24,25,0,3,0,8.000000,3,1,21.0750,S
25,26,1,3,0,38.000000,1,5,31.3875,S
26,27,0,3,1,29.699118,0,0,7.2250,C
27,28,0,1,1,19.000000,3,2,263.0000,S
28,29,1,3,0,29.699118,0,0,7.8792,Q
29,30,0,3,1,29.699118,0,0,7.8958,S
...,...,...,...,...,...,...,...,...,...
861,862,0,2,1,21.000000,1,0,11.5000,S
862,863,1,1,0,48.000000,0,0,25.9292,S
863,864,0,3,0,29.699118,8,2,69.5500,S
864,865,0,2,1,24.000000,0,0,13.0000,S
865,866,1,2,0,42.000000,0,0,13.0000,S
866,867,1,2,0,27.000000,1,0,13.8583,C
867,868,0,1,1,31.000000,0,0,50.4958,S
868,869,0,3,1,29.699118,0,0,9.5000,S
869,870,1,3,1,4.000000,1,1,11.1333,S
870,871,0,3,1,26.000000,0,0,7.8958,S
871,872,1,1,0,47.000000,1,1,52.5542,S
872,873,0,1,1,33.000000,0,0,5.0000,S
873,874,0,3,1,47.000000,0,0,9.0000,S
874,875,1,2,0,28.000000,1,0,24.0000,C
875,876,1,3,0,15.000000,0,0,7.2250,C
876,877,0,3,1,20.000000,0,0,9.8458,S
877,878,0,3,1,19.000000,0,0,7.8958,S
878,879,0,3,1,29.699118,0,0,7.8958,S
879,880,1,1,0,56.000000,0,1,83.1583,C
880,881,1,2,0,25.000000,0,1,26.0000,S
881,882,0,3,1,33.000000,0,0,7.8958,S
882,883,0,3,0,22.000000,0,0,10.5167,S
883,884,0,2,1,28.000000,0,0,10.5000,S
884,885,0,3,1,25.000000,0,0,7.0500,S
885,886,0,3,0,39.000000,0,5,29.1250,Q
886,887,0,2,1,27.000000,0,0,13.0000,S
887,888,1,1,0,19.000000,0,0,30.0000,S
888,889,0,3,0,29.699118,1,2,23.4500,S
889,890,1,1,1,26.000000,0,0,30.0000,C
890,891,0,3,1,32.000000,0,0,7.7500,Q

In [7]:
pd.unique(df1.Embarked)

array(['S', 'C', 'Q', nan], dtype=object)

In [8]:
df1.groupby('Embarked').count()

          PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare
Embarked
C                 168       168     168  168  168    168    168   168
Q                  77        77      77   77   77     77     77    77
S                 644       644     644  644  644    644    644   644

In [9]:
df1.head()

   PassengerId  Survived  Pclass Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3   1  22.0      1      0   7.2500        S
1            2         1       1   0  38.0      1      0  71.2833        C
2            3         1       3   0  26.0      0      0   7.9250        S
3            4         1       1   0  35.0      1      0  53.1000        S
4            5         0       3   1  35.0      0      0   8.0500        S

In [10]:
df1 = df1.assign(Embarked=(df1['Embarked'] == 'S').astype(int))

In [11]:
df1.head()

   PassengerId  Survived  Pclass Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3   1  22.0      1      0   7.2500         1
1            2         1       1   0  38.0      1      0  71.2833         0
2            3         1       3   0  26.0      0      0   7.9250         1
3            4         1       1   0  35.0      1      0  53.1000         1
4            5         0       3   1  35.0      0      0   8.0500         1

In [12]:
X = df1.drop(['PassengerId', 'Survived'], axis=1)
y = df1['Survived']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [15]:
from catboost import CatBoostClassifier

In [16]:
model = CatBoostClassifier(iterations=1000)

In [17]:
model.fit(X_train, y_train)

Learning rate set to 0.008911
0:	learn: 0.6876447	total: 50.9ms	remaining: 50.9s
1:	learn: 0.6815969	total: 52.4ms	remaining: 26.1s
2:	learn: 0.6753825	total: 53.8ms	remaining: 17.9s
3:	learn: 0.6698941	total: 55.2ms	remaining: 13.7s
4:	learn: 0.6652935	total: 56.1ms	remaining: 11.2s
5:	learn: 0.6607678	total: 57.2ms	remaining: 9.48s
6:	learn: 0.6550781	total: 58.7ms	remaining: 8.32s
7:	learn: 0.6500375	total: 60ms	remaining: 7.45s
8:	learn: 0.6458929	total: 61.4ms	remaining: 6.76s
9:	learn: 0.6415818	total: 62.7ms	remaining: 6.21s
10:	learn: 0.6372067	total: 64.1ms	remaining: 5.76s
11:	learn: 0.6328163	total: 65.5ms	remaining: 5.39s
12:	learn: 0.6289411	total: 66.9ms	remaining: 5.08s
13:	learn: 0.6252988	total: 67.6ms	remaining: 4.76s
14:	learn: 0.6205084	total: 69.1ms	remaining: 4.54s
15:	learn: 0.6182475	total: 69.7ms	remaining: 4.29s
16:	learn: 0.6134987	total: 71.1ms	remaining: 4.11s
17:	learn: 0.6093441	total: 72.5ms	remaining: 3.95s
18:	learn: 0.6053348	total: 73.6ms	remaining: 3.8s
19:	learn: 0.6011456	total: 75.1ms	remaining: 3.68s
20:	learn: 0.5975724	total: 76.3ms	remaining: 3.56s
21:	learn: 0.5938395	total: 77.7ms	remaining: 3.45s
22:	learn: 0.5902796	total: 79.1ms	remaining: 3.36s
23:	learn: 0.5864469	total: 80.5ms	remaining: 3.27s
24:	learn: 0.5829638	total: 81.9ms	remaining: 3.19s
25:	learn: 0.5793372	total: 83.4ms	remaining: 3.12s
26:	learn: 0.5754762	total: 84.8ms	remaining: 3.06s
27:	learn: 0.5719548	total: 86.2ms	remaining: 2.99s
28:	learn: 0.5683516	total: 87.7ms	remaining: 2.94s
29:	learn: 0.5647582	total: 89.2ms	remaining: 2.88s
30:	learn: 0.5618513	total: 90.7ms	remaining: 2.84s
31:	learn: 0.5594205	total: 91.9ms	remaining: 2.78s
32:	learn: 0.5564337	total: 93.3ms	remaining: 2.73s
33:	learn: 0.5537186	total: 94.7ms	remaining: 2.69s
34:	learn: 0.5511357	total: 95.9ms	remaining: 2.64s
35:	learn: 0.5497152	total: 96.7ms	remaining: 2.59s
36:	learn: 0.5470321	total: 98.1ms	remaining: 2.55s
37:	learn: 0.5445832	total: 99.6ms	remaining: 2.52s
38:	learn: 0.5420987	total: 101ms	remaining: 2.5s
39:	learn: 0.5393836	total: 103ms	remaining: 2.48s
40:	learn: 0.5365728	total: 105ms	remaining: 2.46s
41:	learn: 0.5340096	total: 107ms	remaining: 2.45s
42:	learn: 0.5312895	total: 109ms	remaining: 2.43s
43:	learn: 0.5287654	total: 111ms	remaining: 2.41s
44:	learn: 0.5268912	total: 112ms	remaining: 2.38s
45:	learn: 0.5241544	total: 114ms	remaining: 2.36s
46:	learn: 0.5219259	total: 115ms	remaining: 2.34s
47:	learn: 0.5195569	total: 117ms	remaining: 2.32s
48:	learn: 0.5171922	total: 118ms	remaining: 2.3s
49:	learn: 0.5145137	total: 120ms	remaining: 2.28s
50:	learn: 0.5125487	total: 121ms	remaining: 2.25s
51:	learn: 0.5102871	total: 123ms	remaining: 2.23s
52:	learn: 0.5087821	total: 124ms	remaining: 2.21s
53:	learn: 0.5064326	total: 125ms	remaining: 2.19s
54:	learn: 0.5044351	total: 126ms	remaining: 2.17s
55:	learn: 0.5034825	total: 127ms	remaining: 2.14s
56:	learn: 0.5018263	total: 128ms	remaining: 2.12s
57:	learn: 0.4998306	total: 130ms	remaining: 2.11s
58:	learn: 0.4980862	total: 131ms	remaining: 2.09s
59:	learn: 0.4958648	total: 133ms	remaining: 2.08s
60:	learn: 0.4937938	total: 134ms	remaining: 2.06s
61:	learn: 0.4916681	total: 135ms	remaining: 2.05s
62:	learn: 0.4899248	total: 137ms	remaining: 2.03s
63:	learn: 0.4882076	total: 138ms	remaining: 2.02s
64:	learn: 0.4862446	total: 140ms	remaining: 2.01s
65:	learn: 0.4846890	total: 141ms	remaining: 1.99s
66:	learn: 0.4829322	total: 142ms	remaining: 1.98s
67:	learn: 0.4812021	total: 144ms	remaining: 1.97s
68:	learn: 0.4798076	total: 145ms	remaining: 1.96s
69:	learn: 0.4782230	total: 146ms	remaining: 1.95s
70:	learn: 0.4765590	total: 148ms	remaining: 1.94s
71:	learn: 0.4746829	total: 149ms	remaining: 1.92s
72:	learn: 0.4732640	total: 151ms	remaining: 1.92s
73:	learn: 0.4717675	total: 153ms	remaining: 1.91s
74:	learn: 0.4705268	total: 154ms	remaining: 1.9s
75:	learn: 0.4698968	total: 155ms	remaining: 1.89s
76:	learn: 0.4686070	total: 157ms	remaining: 1.88s
77:	learn: 0.4674789	total: 158ms	remaining: 1.87s
78:	learn: 0.4662798	total: 159ms	remaining: 1.86s
79:	learn: 0.4648525	total: 161ms	remaining: 1.85s
80:	learn: 0.4634271	total: 162ms	remaining: 1.84s
81:	learn: 0.4620715	total: 164ms	remaining: 1.83s
82:	learn: 0.4608374	total: 165ms	remaining: 1.82s
83:	learn: 0.4594974	total: 166ms	remaining: 1.81s
84:	learn: 0.4584907	total: 168ms	remaining: 1.8s
85:	learn: 0.4572992	total: 169ms	remaining: 1.79s
86:	learn: 0.4560021	total: 170ms	remaining: 1.79s
87:	learn: 0.4550173	total: 172ms	remaining: 1.78s
88:	learn: 0.4545840	total: 172ms	remaining: 1.76s
89:	learn: 0.4535626	total: 173ms	remaining: 1.75s
90:	learn: 0.4525286	total: 175ms	remaining: 1.75s
91:	learn: 0.4521144	total: 176ms	remaining: 1.73s
92:	learn: 0.4513061	total: 177ms	remaining: 1.73s
93:	learn: 0.4500762	total: 178ms	remaining: 1.72s
94:	learn: 0.4490629	total: 180ms	remaining: 1.71s
95:	learn: 0.4481534	total: 181ms	remaining: 1.7s
96:	learn: 0.4472128	total: 182ms	remaining: 1.69s
97:	learn: 0.4462819	total: 183ms	remaining: 1.68s
98:	learn: 0.4451657	total: 184ms	remaining: 1.68s
99:	learn: 0.4446355	total: 185ms	remaining: 1.67s
100:	learn: 0.4434447	total: 186ms	remaining: 1.66s
101:	learn: 0.4424086	total: 187ms	remaining: 1.65s
102:	learn: 0.4412332	total: 189ms	remaining: 1.64s
103:	learn: 0.4407136	total: 190ms	remaining: 1.64s
104:	learn: 0.4401328	total: 191ms	remaining: 1.63s
105:	learn: 0.4391728	total: 192ms	remaining: 1.62s
106:	learn: 0.4380713	total: 193ms	remaining: 1.61s
107:	learn: 0.4373887	total: 195ms	remaining: 1.61s
108:	learn: 0.4364856	total: 196ms	remaining: 1.6s
109:	learn: 0.4359868	total: 197ms	remaining: 1.59s
110:	learn: 0.4350404	total: 198ms	remaining: 1.59s
111:	learn: 0.4340231	total: 200ms	remaining: 1.58s
112:	learn: 0.4331395	total: 201ms	remaining: 1.58s
113:	learn: 0.4323923	total: 202ms	remaining: 1.57s
114:	learn: 0.4315482	total: 203ms	remaining: 1.56s
115:	learn: 0.4309707	total: 205ms	remaining: 1.56s
116:	learn: 0.4302784	total: 206ms	remaining: 1.55s
117:	learn: 0.4293655	total: 207ms	remaining: 1.55s
118:	learn: 0.4286035	total: 208ms	remaining: 1.54s
119:	learn: 0.4279358	total: 210ms	remaining: 1.54s
120:	learn: 0.4272100	total: 211ms	remaining: 1.53s
121:	learn: 0.4265214	total: 213ms	remaining: 1.53s
122:	learn: 0.4257840	total: 214ms	remaining: 1.53s
123:	learn: 0.4255735	total: 215ms	remaining: 1.52s
124:	learn: 0.4252860	total: 216ms	remaining: 1.51s
125:	learn: 0.4248384	total: 217ms	remaining: 1.5s
126:	learn: 0.4240415	total: 219ms	remaining: 1.5s
127:	learn: 0.4235788	total: 220ms	remaining: 1.5s
128:	learn: 0.4228963	total: 222ms	remaining: 1.5s
129:	learn: 0.4222921	total: 223ms	remaining: 1.49s
130:	learn: 0.4215580	total: 225ms	remaining: 1.49s
131:	learn: 0.4211530	total: 226ms	remaining: 1.48s
132:	learn: 0.4204521	total: 227ms	remaining: 1.48s
133:	learn: 0.4197860	total: 229ms	remaining: 1.48s
134:	learn: 0.4194033	total: 230ms	remaining: 1.48s
135:	learn: 0.4185782	total: 232ms	remaining: 1.47s
136:	learn: 0.4181111	total: 233ms	remaining: 1.47s
137:	learn: 0.4173922	total: 235ms	remaining: 1.47s
138:	learn: 0.4168352	total: 236ms	remaining: 1.46s
139:	learn: 0.4161359	total: 238ms	remaining: 1.46s
140:	learn: 0.4153829	total: 239ms	remaining: 1.46s
141:	learn: 0.4147848	total: 241ms	remaining: 1.46s
142:	learn: 0.4143386	total: 243ms	remaining: 1.45s
143:	learn: 0.4140161	total: 244ms	remaining: 1.45s
144:	learn: 0.4134493	total: 245ms	remaining: 1.45s
145:	learn: 0.4130056	total: 247ms	remaining: 1.44s
146:	learn: 0.4127044	total: 248ms	remaining: 1.44s
147:	learn: 0.4121006	total: 250ms	remaining: 1.44s
148:	learn: 0.4116919	total: 251ms	remaining: 1.44s
149:	learn: 0.4110718	total: 253ms	remaining: 1.43s
150:	learn: 0.4108109	total: 254ms	remaining: 1.43s
151:	learn: 0.4106900	total: 255ms	remaining: 1.42s
152:	learn: 0.4104750	total: 255ms	remaining: 1.41s
153:	learn: 0.4101048	total: 257ms	remaining: 1.41s
154:	learn: 0.4097352	total: 258ms	remaining: 1.41s
155:	learn: 0.4092250	total: 259ms	remaining: 1.4s
156:	learn: 0.4090175	total: 260ms	remaining: 1.4s
157:	learn: 0.4087076	total: 261ms	remaining: 1.39s
158:	learn: 0.4083134	total: 262ms	remaining: 1.39s
159:	learn: 0.4078443	total: 264ms	remaining: 1.38s
160:	learn: 0.4072918	total: 265ms	remaining: 1.38s
161:	learn: 0.4068284	total: 266ms	remaining: 1.38s
162:	learn: 0.4063939	total: 268ms	remaining: 1.37s
163:	learn: 0.4061427	total: 269ms	remaining: 1.37s
164:	learn: 0.4057116	total: 270ms	remaining: 1.36s
165:	learn: 0.4051315	total: 271ms	remaining: 1.36s
166:	learn: 0.4048617	total: 273ms	remaining: 1.36s
167:	learn: 0.4044052	total: 274ms	remaining: 1.36s
168:	learn: 0.4039128	total: 276ms	remaining: 1.36s
169:	learn: 0.4036475	total: 278ms	remaining: 1.35s
170:	learn: 0.4032797	total: 279ms	remaining: 1.35s
171:	learn: 0.4029639	total: 281ms	remaining: 1.35s
172:	learn: 0.4026891	total: 283ms	remaining: 1.35s
173:	learn: 0.4023650	total: 285ms	remaining: 1.35s
174:	learn: 0.4021050	total: 286ms	remaining: 1.35s
175:	learn: 0.4020368	total: 287ms	remaining: 1.34s
176:	learn: 0.4015822	total: 289ms	remaining: 1.34s
177:	learn: 0.4011355	total: 290ms	remaining: 1.34s
178:	learn: 0.4006560	total: 293ms	remaining: 1.34s
179:	learn: 0.4000642	total: 295ms	remaining: 1.34s
180:	learn: 0.3997527	total: 296ms	remaining: 1.34s
181:	learn: 0.3993233	total: 298ms	remaining: 1.34s
182:	learn: 0.3989644	total: 300ms	remaining: 1.34s
183:	learn: 0.3986289	total: 302ms	remaining: 1.34s
184:	learn: 0.3982069	total: 303ms	remaining: 1.34s
185:	learn: 0.3978722	total: 305ms	remaining: 1.33s
186:	learn: 0.3975595	total: 307ms	remaining: 1.33s
187:	learn: 0.3970834	total: 308ms	remaining: 1.33s
188:	learn: 0.3966748	total: 310ms	remaining: 1.33s
189:	learn: 0.3963067	total: 311ms	remaining: 1.33s
190:	learn: 0.3957501	total: 313ms	remaining: 1.32s
191:	learn: 0.3953275	total: 315ms	remaining: 1.32s
192:	learn: 0.3947987	total: 316ms	remaining: 1.32s
193:	learn: 0.3944242	total: 319ms	remaining: 1.32s
194:	learn: 0.3942430	total: 320ms	remaining: 1.32s
195:	learn: 0.3938358	total: 321ms	remaining: 1.32s
196:	learn: 0.3935575	total: 323ms	remaining: 1.32s
197:	learn: 0.3934977	total: 324ms	remaining: 1.31s
198:	learn: 0.3931352	total: 325ms	remaining: 1.31s

199:	learn: 0.3929928	total: 328ms	remaining: 1.31s
200:	learn: 0.3925736	total: 329ms	remaining: 1.31s
201:	learn: 0.3922132	total: 330ms	remaining: 1.3s
202:	learn: 0.3919148	total: 332ms	remaining: 1.3s
203:	learn: 0.3915957	total: 334ms	remaining: 1.3s
204:	learn: 0.3912342	total: 335ms	remaining: 1.3s
205:	learn: 0.3908396	total: 337ms	remaining: 1.3s
206:	learn: 0.3906303	total: 338ms	remaining: 1.3s
207:	learn: 0.3902161	total: 340ms	remaining: 1.29s
208:	learn: 0.3898805	total: 342ms	remaining: 1.29s
209:	learn: 0.3894524	total: 343ms	remaining: 1.29s
210:	learn: 0.3891009	total: 345ms	remaining: 1.29s
211:	learn: 0.3890100	total: 345ms	remaining: 1.28s
212:	learn: 0.3886565	total: 347ms	remaining: 1.28s
213:	learn: 0.3885101	total: 349ms	remaining: 1.28s
214:	learn: 0.3882041	total: 350ms	remaining: 1.28s
215:	learn: 0.3878996	total: 352ms	remaining: 1.28s
216:	learn: 0.3877574	total: 354ms	remaining: 1.27s
217:	learn: 0.3874580	total: 355ms	remaining: 1.27s
218:	learn: 0.3870751	total: 357ms	remaining: 1.27s
219:	learn: 0.3868687	total: 358ms	remaining: 1.27s
220:	learn: 0.3866092	total: 360ms	remaining: 1.27s
221:	learn: 0.3863862	total: 361ms	remaining: 1.26s
222:	learn: 0.3861564	total: 363ms	remaining: 1.26s
223:	learn: 0.3859661	total: 364ms	remaining: 1.26s
224:	learn: 0.3857982	total: 366ms	remaining: 1.26s
225:	learn: 0.3855301	total: 367ms	remaining: 1.26s
226:	learn: 0.3852711	total: 369ms	remaining: 1.25s
227:	learn: 0.3852462	total: 370ms	remaining: 1.25s
228:	learn: 0.3849761	total: 371ms	remaining: 1.25s
229:	learn: 0.3849411	total: 372ms	remaining: 1.25s
230:	learn: 0.3846307	total: 374ms	remaining: 1.24s
231:	learn: 0.3844411	total: 376ms	remaining: 1.24s
232:	learn: 0.3842400	total: 379ms	remaining: 1.25s
233:	learn: 0.3841897	total: 380ms	remaining: 1.24s
234:	learn: 0.3840775	total: 381ms	remaining: 1.24s
235:	learn: 0.3839412	total: 383ms	remaining: 1.24s
236:	learn: 0.3836868	total: 384ms	remaining: 1.24s
237:	learn: 0.3835749	total: 385ms	remaining: 1.23s
238:	learn: 0.3833380	total: 387ms	remaining: 1.23s
239:	learn: 0.3831116	total: 388ms	remaining: 1.23s
240:	learn: 0.3826972	total: 390ms	remaining: 1.23s
241:	learn: 0.3824833	total: 391ms	remaining: 1.23s
242:	learn: 0.3823685	total: 393ms	remaining: 1.23s
243:	learn: 0.3821252	total: 395ms	remaining: 1.22s
244:	learn: 0.3819209	total: 396ms	remaining: 1.22s
245:	learn: 0.3816598	total: 397ms	remaining: 1.22s
246:	learn: 0.3814743	total: 398ms	remaining: 1.21s
247:	learn: 0.3812269	total: 400ms	remaining: 1.21s
248:	learn: 0.3809598	total: 401ms	remaining: 1.21s
249:	learn: 0.3807993	total: 402ms	remaining: 1.21s
250:	learn: 0.3807725	total: 403ms	remaining: 1.2s
251:	learn: 0.3805727	total: 404ms	remaining: 1.2s
252:	learn: 0.3801962	total: 406ms	remaining: 1.2s
253:	learn: 0.3797764	total: 407ms	remaining: 1.2s
254:	learn: 0.3795800	total: 409ms	remaining: 1.19s
255:	learn: 0.3794031	total: 410ms	remaining: 1.19s
256:	learn: 0.3791215	total: 411ms	remaining: 1.19s
257:	learn: 0.3788503	total: 413ms	remaining: 1.19s
258:	learn: 0.3786631	total: 414ms	remaining: 1.18s
259:	learn: 0.3783750	total: 415ms	remaining: 1.18s
260:	learn: 0.3782208	total: 416ms	remaining: 1.18s
261:	learn: 0.3779652	total: 418ms	remaining: 1.18s
262:	learn: 0.3778180	total: 420ms	remaining: 1.18s
263:	learn: 0.3776725	total: 421ms	remaining: 1.17s
264:	learn: 0.3775376	total: 422ms	remaining: 1.17s
265:	learn: 0.3773178	total: 424ms	remaining: 1.17s
266:	learn: 0.3771920	total: 425ms	remaining: 1.17s
267:	learn: 0.3770456	total: 426ms	remaining: 1.16s
268:	learn: 0.3766209	total: 427ms	remaining: 1.16s
269:	learn: 0.3764717	total: 429ms	remaining: 1.16s
270:	learn: 0.3760586	total: 430ms	remaining: 1.16s
271:	learn: 0.3758978	total: 431ms	remaining: 1.15s
272:	learn: 0.3757731	total: 433ms	remaining: 1.15s
273:	learn: 0.3755031	total: 434ms	remaining: 1.15s
274:	learn: 0.3753931	total: 435ms	remaining: 1.15s
275:	learn: 0.3751288	total: 437ms	remaining: 1.15s
276:	learn: 0.3749708	total: 438ms	remaining: 1.14s
277:	learn: 0.3747085	total: 439ms	remaining: 1.14s
278:	learn: 0.3742914	total: 441ms	remaining: 1.14s
279:	learn: 0.3740617	total: 442ms	remaining: 1.14s
280:	learn: 0.3739182	total: 443ms	remaining: 1.13s
281:	learn: 0.3738038	total: 444ms	remaining: 1.13s
282:	learn: 0.3736268	total: 446ms	remaining: 1.13s
283:	learn: 0.3734698	total: 447ms	remaining: 1.13s
284:	learn: 0.3733204	total: 448ms	remaining: 1.12s
285:	learn: 0.3732235	total: 449ms	remaining: 1.12s
286:	learn: 0.3730184	total: 451ms	remaining: 1.12s
287:	learn: 0.3724909	total: 452ms	remaining: 1.12s
288:	learn: 0.3724462	total: 453ms	remaining: 1.11s
289:	learn: 0.3724235	total: 454ms	remaining: 1.11s
290:	learn: 0.3723637	total: 455ms	remaining: 1.11s
291:	learn: 0.3721646	total: 456ms	remaining: 1.11s
292:	learn: 0.3720096	total: 457ms	remaining: 1.1s
293:	learn: 0.3717170	total: 459ms	remaining: 1.1s
294:	learn: 0.3714449	total: 460ms	remaining: 1.1s
295:	learn: 0.3713555	total: 461ms	remaining: 1.1s
296:	learn: 0.3712069	total: 463ms	remaining: 1.09s
297:	learn: 0.3709818	total: 464ms	remaining: 1.09s
298:	learn: 0.3708404	total: 465ms	remaining: 1.09s
299:	learn: 0.3707541	total: 466ms	remaining: 1.09s
300:	learn: 0.3704749	total: 468ms	remaining: 1.09s
301:	learn: 0.3701480	total: 469ms	remaining: 1.08s
302:	learn: 0.3700803	total: 470ms	remaining: 1.08s
303:	learn: 0.3698823	total: 471ms	remaining: 1.08s
304:	learn: 0.3694532	total: 473ms	remaining: 1.08s
305:	learn: 0.3691227	total: 474ms	remaining: 1.07s
306:	learn: 0.3689884	total: 475ms	remaining: 1.07s
307:	learn: 0.3687693	total: 477ms	remaining: 1.07s
308:	learn: 0.3684688	total: 478ms	remaining: 1.07s
309:	learn: 0.3682307	total: 479ms	remaining: 1.07s
310:	learn: 0.3681821	total: 480ms	remaining: 1.06s
311:	learn: 0.3678742	total: 481ms	remaining: 1.06s
312:	learn: 0.3677486	total: 483ms	remaining: 1.06s
313:	learn: 0.3675284	total: 485ms	remaining: 1.06s
314:	learn: 0.3672795	total: 486ms	remaining: 1.06s
315:	learn: 0.3671130	total: 488ms	remaining: 1.05s
316:	learn: 0.3668787	total: 489ms	remaining: 1.05s
317:	learn: 0.3667380	total: 491ms	remaining: 1.05s
318:	learn: 0.3666697	total: 492ms	remaining: 1.05s
319:	learn: 0.3663971	total: 494ms	remaining: 1.05s
320:	learn: 0.3661255	total: 496ms	remaining: 1.05s
321:	learn: 0.3659018	total: 497ms	remaining: 1.05s
322:	learn: 0.3657178	total: 499ms	remaining: 1.04s
323:	learn: 0.3654399	total: 500ms	remaining: 1.04s
324:	learn: 0.3652734	total: 501ms	remaining: 1.04s
325:	learn: 0.3651574	total: 503ms	remaining: 1.04s
326:	learn: 0.3651080	total: 504ms	remaining: 1.04s
327:	learn: 0.3649436	total: 505ms	remaining: 1.03s
328:	learn: 0.3647947	total: 507ms	remaining: 1.03s
329:	learn: 0.3646233	total: 508ms	remaining: 1.03s
330:	learn: 0.3644633	total: 509ms	remaining: 1.03s
331:	learn: 0.3643358	total: 510ms	remaining: 1.03s
332:	learn: 0.3643105	total: 511ms	remaining: 1.02s
333:	learn: 0.3640346	total: 512ms	remaining: 1.02s
334:	learn: 0.3638438	total: 514ms	remaining: 1.02s
335:	learn: 0.3636506	total: 515ms	remaining: 1.02s
336:	learn: 0.3633935	total: 517ms	remaining: 1.02s
337:	learn: 0.3630998	total: 518ms	remaining: 1.01s
338:	learn: 0.3628401	total: 519ms	remaining: 1.01s
339:	learn: 0.3626687	total: 520ms	remaining: 1.01s
340:	learn: 0.3625819	total: 522ms	remaining: 1.01s
341:	learn: 0.3624593	total: 523ms	remaining: 1.01s
342:	learn: 0.3623507	total: 524ms	remaining: 1s
343:	learn: 0.3621587	total: 526ms	remaining: 1s
344:	learn: 0.3621102	total: 526ms	remaining: 999ms
345:	learn: 0.3618989	total: 528ms	remaining: 997ms
346:	learn: 0.3618691	total: 529ms	remaining: 995ms
347:	learn: 0.3618226	total: 530ms	remaining: 993ms
348:	learn: 0.3617781	total: 531ms	remaining: 991ms
349:	learn: 0.3616816	total: 532ms	remaining: 988ms
350:	learn: 0.3616512	total: 533ms	remaining: 985ms
351:	learn: 0.3614383	total: 534ms	remaining: 983ms
352:	learn: 0.3612263	total: 535ms	remaining: 981ms
353:	learn: 0.3611756	total: 536ms	remaining: 979ms
354:	learn: 0.3610925	total: 538ms	remaining: 977ms
355:	learn: 0.3609247	total: 539ms	remaining: 975ms
356:	learn: 0.3606628	total: 540ms	remaining: 973ms
357:	learn: 0.3603017	total: 542ms	remaining: 971ms
358:	learn: 0.3602765	total: 542ms	remaining: 968ms
359:	learn: 0.3601353	total: 544ms	remaining: 966ms
360:	learn: 0.3599645	total: 545ms	remaining: 965ms
361:	learn: 0.3598148	total: 546ms	remaining: 963ms
362:	learn: 0.3595554	total: 548ms	remaining: 961ms
363:	learn: 0.3595049	total: 549ms	remaining: 958ms
364:	learn: 0.3594236	total: 550ms	remaining: 957ms
365:	learn: 0.3590166	total: 551ms	remaining: 955ms
366:	learn: 0.3589399	total: 552ms	remaining: 952ms
367:	learn: 0.3588546	total: 554ms	remaining: 951ms
368:	learn: 0.3587454	total: 555ms	remaining: 949ms
369:	learn: 0.3584650	total: 556ms	remaining: 947ms
370:	learn: 0.3583422	total: 557ms	remaining: 945ms
371:	learn: 0.3581010	total: 559ms	remaining: 943ms
372:	learn: 0.3578886	total: 560ms	remaining: 941ms
373:	learn: 0.3576384	total: 561ms	remaining: 939ms
374:	learn: 0.3575822	total: 562ms	remaining: 937ms
375:	learn: 0.3574544	total: 564ms	remaining: 936ms
376:	learn: 0.3572334	total: 565ms	remaining: 934ms
377:	learn: 0.3571890	total: 566ms	remaining: 932ms
378:	learn: 0.3570721	total: 568ms	remaining: 930ms
379:	learn: 0.3569185	total: 569ms	remaining: 928ms
380:	learn: 0.3567619	total: 570ms	remaining: 926ms
381:	learn: 0.3566799	total: 571ms	remaining: 924ms
382:	learn: 0.3565096	total: 573ms	remaining: 922ms
383:	learn: 0.3563887	total: 574ms	remaining: 920ms
384:	learn: 0.3561040	total: 575ms	remaining: 919ms
385:	learn: 0.3558844	total: 576ms	remaining: 917ms
386:	learn: 0.3557886	total: 578ms	remaining: 915ms
387:	learn: 0.3556750	total: 579ms	remaining: 913ms
388:	learn: 0.3554565	total: 580ms	remaining: 911ms
389:	learn: 0.3554184	total: 581ms	remaining: 909ms
390:	learn: 0.3553796	total: 582ms	remaining: 907ms
391:	learn: 0.3553234	total: 584ms	remaining: 905ms
392:	learn: 0.3551868	total: 585ms	remaining: 903ms
393:	learn: 0.3549766	total: 586ms	remaining: 901ms
394:	learn: 0.3547885	total: 587ms	remaining: 900ms
395:	learn: 0.3546911	total: 589ms	remaining: 898ms
396:	learn: 0.3546504	total: 590ms	remaining: 896ms
397:	learn: 0.3545570	total: 591ms	remaining: 894ms
398:	learn: 0.3543770	total: 592ms	remaining: 892ms
399:	learn: 0.3542916	total: 594ms	remaining: 891ms
400:	learn: 0.3541868	total: 595ms	remaining: 889ms
401:	learn: 0.3540360	total: 596ms	remaining: 887ms
402:	learn: 0.3539390	total: 598ms	remaining: 885ms
403:	learn: 0.3537969	total: 599ms	remaining: 883ms
404:	learn: 0.3537342	total: 600ms	remaining: 882ms
405:	learn: 0.3533447	total: 601ms	remaining: 880ms
406:	learn: 0.3531280	total: 603ms	remaining: 878ms
407:	learn: 0.3530399	total: 604ms	remaining: 877ms
408:	learn: 0.3527531	total: 606ms	remaining: 875ms
409:	learn: 0.3527044	total: 607ms	remaining: 873ms
410:	learn: 0.3525483	total: 608ms	remaining: 871ms
411:	learn: 0.3525027	total: 609ms	remaining: 870ms
412:	learn: 0.3523304	total: 611ms	remaining: 868ms
413:	learn: 0.3521754	total: 612ms	remaining: 867ms
414:	learn: 0.3521367	total: 614ms	remaining: 865ms
415:	learn: 0.3520293	total: 615ms	remaining: 863ms
416:	learn: 0.3519413	total: 616ms	remaining: 862ms
417:	learn: 0.3516470	total: 618ms	remaining: 860ms
418:	learn: 0.3515510	total: 619ms	remaining: 858ms
419:	learn: 0.3514725	total: 620ms	remaining: 856ms
420:	learn: 0.3513804	total: 621ms	remaining: 854ms
421:	learn: 0.3511237	total: 623ms	remaining: 853ms
422:	learn: 0.3509432	total: 624ms	remaining: 851ms
423:	learn: 0.3507441	total: 625ms	remaining: 849ms
424:	learn: 0.3506672	total: 626ms	remaining: 847ms
425:	learn: 0.3506527	total: 627ms	remaining: 845ms
426:	learn: 0.3504734	total: 629ms	remaining: 843ms
427:	learn: 0.3504347	total: 630ms	remaining: 841ms
428:	learn: 0.3502483	total: 631ms	remaining: 840ms
429:	learn: 0.3501278	total: 632ms	remaining: 838ms
430:	learn: 0.3500808	total: 633ms	remaining: 836ms
431:	learn: 0.3499529	total: 634ms	remaining: 834ms
432:	learn: 0.3498783	total: 638ms	remaining: 836ms
433:	learn: 0.3498605	total: 639ms	remaining: 834ms
434:	learn: 0.3495049	total: 640ms	remaining: 832ms
435:	learn: 0.3493917	total: 642ms	remaining: 830ms

436:	learn: 0.3493316	total: 643ms	remaining: 829ms
437:	learn: 0.3492492	total: 645ms	remaining: 827ms
438:	learn: 0.3490756	total: 646ms	remaining: 826ms
439:	learn: 0.3489170	total: 648ms	remaining: 825ms
440:	learn: 0.3487563	total: 650ms	remaining: 823ms
441:	learn: 0.3486425	total: 651ms	remaining: 822ms
442:	learn: 0.3484682	total: 653ms	remaining: 821ms
443:	learn: 0.3483449	total: 654ms	remaining: 819ms
444:	learn: 0.3482195	total: 656ms	remaining: 818ms
445:	learn: 0.3481532	total: 657ms	remaining: 817ms
446:	learn: 0.3479307	total: 659ms	remaining: 815ms
447:	learn: 0.3478196	total: 660ms	remaining: 814ms
448:	learn: 0.3476755	total: 662ms	remaining: 813ms
449:	learn: 0.3476158	total: 664ms	remaining: 811ms
450:	learn: 0.3475229	total: 665ms	remaining: 810ms
451:	learn: 0.3474882	total: 667ms	remaining: 809ms
452:	learn: 0.3473346	total: 668ms	remaining: 807ms
453:	learn: 0.3472987	total: 670ms	remaining: 806ms
454:	learn: 0.3472817	total: 672ms	remaining: 805ms
455:	learn: 0.3471177	total: 673ms	remaining: 803ms
456:	learn: 0.3470572	total: 675ms	remaining: 802ms
457:	learn: 0.3469457	total: 676ms	remaining: 800ms
458:	learn: 0.3469208	total: 677ms	remaining: 798ms
459:	learn: 0.3467931	total: 678ms	remaining: 796ms
460:	learn: 0.3467266	total: 679ms	remaining: 794ms
461:	learn: 0.3466497	total: 680ms	remaining: 792ms
462:	learn: 0.3465870	total: 681ms	remaining: 790ms
463:	learn: 0.3464282	total: 683ms	remaining: 789ms
464:	learn: 0.3462796	total: 684ms	remaining: 787ms
465:	learn: 0.3460616	total: 685ms	remaining: 786ms
466:	learn: 0.3458682	total: 687ms	remaining: 784ms
467:	learn: 0.3458402	total: 688ms	remaining: 782ms
468:	learn: 0.3457537	total: 689ms	remaining: 781ms
469:	learn: 0.3456597	total: 691ms	remaining: 779ms
470:	learn: 0.3456082	total: 692ms	remaining: 777ms
471:	learn: 0.3452458	total: 693ms	remaining: 776ms
472:	learn: 0.3450852	total: 695ms	remaining: 774ms
473:	learn: 0.3450205	total: 696ms	remaining: 772ms
474:	learn: 0.3448083	total: 697ms	remaining: 770ms
475:	learn: 0.3447497	total: 698ms	remaining: 769ms
476:	learn: 0.3446255	total: 700ms	remaining: 767ms
477:	learn: 0.3444875	total: 701ms	remaining: 766ms
478:	learn: 0.3443781	total: 702ms	remaining: 764ms
479:	learn: 0.3443234	total: 704ms	remaining: 762ms
480:	learn: 0.3441710	total: 705ms	remaining: 761ms
481:	learn: 0.3441511	total: 706ms	remaining: 758ms
482:	learn: 0.3440865	total: 707ms	remaining: 757ms
483:	learn: 0.3439846	total: 708ms	remaining: 755ms
484:	learn: 0.3438824	total: 710ms	remaining: 753ms
485:	learn: 0.3438797	total: 710ms	remaining: 751ms
486:	learn: 0.3438746	total: 711ms	remaining: 749ms
487:	learn: 0.3437252	total: 712ms	remaining: 747ms
488:	learn: 0.3435147	total: 713ms	remaining: 746ms
489:	learn: 0.3433761	total: 715ms	remaining: 744ms
490:	learn: 0.3433363	total: 716ms	remaining: 742ms
491:	learn: 0.3431071	total: 718ms	remaining: 741ms
492:	learn: 0.3428521	total: 719ms	remaining: 739ms
493:	learn: 0.3426832	total: 720ms	remaining: 738ms
494:	learn: 0.3424800	total: 722ms	remaining: 736ms
495:	learn: 0.3423977	total: 723ms	remaining: 734ms
496:	learn: 0.3422928	total: 724ms	remaining: 733ms
497:	learn: 0.3422262	total: 725ms	remaining: 731ms
498:	learn: 0.3419927	total: 726ms	remaining: 729ms
499:	learn: 0.3419677	total: 728ms	remaining: 728ms
500:	learn: 0.3419319	total: 729ms	remaining: 726ms
501:	learn: 0.3418212	total: 730ms	remaining: 724ms
502:	learn: 0.3415594	total: 731ms	remaining: 723ms
503:	learn: 0.3415029	total: 733ms	remaining: 721ms
504:	learn: 0.3414063	total: 734ms	remaining: 719ms
505:	learn: 0.3412490	total: 735ms	remaining: 718ms
506:	learn: 0.3410517	total: 737ms	remaining: 716ms
507:	learn: 0.3409462	total: 738ms	remaining: 715ms
508:	learn: 0.3408304	total: 739ms	remaining: 713ms
509:	learn: 0.3407905	total: 740ms	remaining: 711ms
510:	learn: 0.3406265	total: 742ms	remaining: 710ms
511:	learn: 0.3405850	total: 743ms	remaining: 708ms
512:	learn: 0.3404422	total: 744ms	remaining: 706ms
513:	learn: 0.3402080	total: 745ms	remaining: 705ms
514:	learn: 0.3401524	total: 747ms	remaining: 703ms
515:	learn: 0.3401465	total: 747ms	remaining: 701ms
516:	learn: 0.3400593	total: 749ms	remaining: 699ms
517:	learn: 0.3400172	total: 750ms	remaining: 698ms
518:	learn: 0.3399117	total: 751ms	remaining: 696ms
519:	learn: 0.3398273	total: 753ms	remaining: 695ms
520:	learn: 0.3397941	total: 754ms	remaining: 693ms
521:	learn: 0.3396021	total: 755ms	remaining: 692ms
522:	learn: 0.3395611	total: 757ms	remaining: 690ms
523:	learn: 0.3394207	total: 758ms	remaining: 688ms
524:	learn: 0.3392758	total: 759ms	remaining: 687ms
525:	learn: 0.3392484	total: 760ms	remaining: 685ms
526:	learn: 0.3391446	total: 762ms	remaining: 684ms
527:	learn: 0.3390467	total: 763ms	remaining: 682ms
528:	learn: 0.3390443	total: 764ms	remaining: 680ms
529:	learn: 0.3390422	total: 764ms	remaining: 678ms
530:	learn: 0.3389863	total: 765ms	remaining: 676ms
531:	learn: 0.3389551	total: 767ms	remaining: 675ms
532:	learn: 0.3389045	total: 768ms	remaining: 673ms
533:	learn: 0.3388046	total: 769ms	remaining: 671ms
534:	learn: 0.3387257	total: 771ms	remaining: 670ms
535:	learn: 0.3386900	total: 772ms	remaining: 668ms
536:	learn: 0.3385467	total: 773ms	remaining: 667ms
537:	learn: 0.3385294	total: 774ms	remaining: 665ms
538:	learn: 0.3383929	total: 775ms	remaining: 663ms
539:	learn: 0.3381126	total: 776ms	remaining: 661ms
540:	learn: 0.3381064	total: 777ms	remaining: 659ms
541:	learn: 0.3379103	total: 778ms	remaining: 658ms
542:	learn: 0.3378218	total: 780ms	remaining: 656ms
543:	learn: 0.3376778	total: 781ms	remaining: 655ms
544:	learn: 0.3375334	total: 782ms	remaining: 653ms
545:	learn: 0.3374044	total: 784ms	remaining: 652ms
546:	learn: 0.3372701	total: 785ms	remaining: 650ms
547:	learn: 0.3369348	total: 786ms	remaining: 648ms
548:	learn: 0.3366016	total: 787ms	remaining: 647ms
549:	learn: 0.3365123	total: 789ms	remaining: 645ms
550:	learn: 0.3363786	total: 790ms	remaining: 644ms
551:	learn: 0.3363413	total: 791ms	remaining: 642ms
552:	learn: 0.3362210	total: 793ms	remaining: 641ms
553:	learn: 0.3361319	total: 794ms	remaining: 639ms
554:	learn: 0.3361236	total: 795ms	remaining: 637ms
555:	learn: 0.3360414	total: 796ms	remaining: 636ms
556:	learn: 0.3359307	total: 797ms	remaining: 634ms
557:	learn: 0.3357506	total: 798ms	remaining: 632ms
558:	learn: 0.3355677	total: 800ms	remaining: 631ms
559:	learn: 0.3354184	total: 801ms	remaining: 630ms
560:	learn: 0.3353803	total: 803ms	remaining: 628ms
561:	learn: 0.3353693	total: 804ms	remaining: 626ms
562:	learn: 0.3352439	total: 806ms	remaining: 625ms
563:	learn: 0.3350988	total: 807ms	remaining: 624ms
564:	learn: 0.3348592	total: 809ms	remaining: 623ms
565:	learn: 0.3347330	total: 811ms	remaining: 622ms
566:	learn: 0.3345640	total: 813ms	remaining: 621ms
567:	learn: 0.3343930	total: 814ms	remaining: 619ms
568:	learn: 0.3343226	total: 816ms	remaining: 618ms
569:	learn: 0.3342571	total: 817ms	remaining: 616ms
570:	learn: 0.3342069	total: 818ms	remaining: 615ms
571:	learn: 0.3340599	total: 820ms	remaining: 613ms
572:	learn: 0.3338893	total: 821ms	remaining: 612ms
573:	learn: 0.3338597	total: 822ms	remaining: 610ms
574:	learn: 0.3337661	total: 823ms	remaining: 608ms
575:	learn: 0.3335882	total: 824ms	remaining: 607ms
576:	learn: 0.3335431	total: 826ms	remaining: 605ms
577:	learn: 0.3332142	total: 827ms	remaining: 604ms
578:	learn: 0.3331962	total: 829ms	remaining: 603ms
579:	learn: 0.3330551	total: 830ms	remaining: 601ms
580:	learn: 0.3329775	total: 831ms	remaining: 600ms
581:	learn: 0.3328403	total: 833ms	remaining: 598ms
582:	learn: 0.3327716	total: 834ms	remaining: 596ms
583:	learn: 0.3325515	total: 835ms	remaining: 595ms
584:	learn: 0.3325393	total: 836ms	remaining: 593ms
585:	learn: 0.3325213	total: 837ms	remaining: 591ms
586:	learn: 0.3324618	total: 838ms	remaining: 590ms
587:	learn: 0.3323279	total: 839ms	remaining: 588ms
588:	learn: 0.3322597	total: 840ms	remaining: 586ms
589:	learn: 0.3322162	total: 842ms	remaining: 585ms
590:	learn: 0.3320508	total: 844ms	remaining: 584ms
591:	learn: 0.3319561	total: 846ms	remaining: 583ms
592:	learn: 0.3318545	total: 848ms	remaining: 582ms
593:	learn: 0.3317797	total: 849ms	remaining: 580ms
594:	learn: 0.3316563	total: 850ms	remaining: 579ms
595:	learn: 0.3315211	total: 852ms	remaining: 577ms
596:	learn: 0.3313835	total: 853ms	remaining: 576ms
597:	learn: 0.3313702	total: 854ms	remaining: 574ms
598:	learn: 0.3313032	total: 855ms	remaining: 573ms
599:	learn: 0.3312169	total: 857ms	remaining: 571ms
600:	learn: 0.3310532	total: 858ms	remaining: 570ms
601:	learn: 0.3310187	total: 859ms	remaining: 568ms
602:	learn: 0.3309747	total: 861ms	remaining: 567ms
603:	learn: 0.3309416	total: 862ms	remaining: 565ms
604:	learn: 0.3308776	total: 863ms	remaining: 563ms
605:	learn: 0.3307634	total: 864ms	remaining: 562ms
606:	learn: 0.3307224	total: 866ms	remaining: 560ms
607:	learn: 0.3306842	total: 867ms	remaining: 559ms
608:	learn: 0.3304585	total: 868ms	remaining: 557ms
609:	learn: 0.3303650	total: 869ms	remaining: 556ms
610:	learn: 0.3303306	total: 871ms	remaining: 554ms
611:	learn: 0.3302302	total: 872ms	remaining: 553ms
612:	learn: 0.3299908	total: 873ms	remaining: 551ms
613:	learn: 0.3298874	total: 875ms	remaining: 550ms
614:	learn: 0.3295798	total: 876ms	remaining: 548ms
615:	learn: 0.3294515	total: 877ms	remaining: 547ms
616:	learn: 0.3292425	total: 878ms	remaining: 545ms
617:	learn: 0.3290191	total: 880ms	remaining: 544ms
618:	learn: 0.3287761	total: 881ms	remaining: 542ms
619:	learn: 0.3286356	total: 882ms	remaining: 541ms
620:	learn: 0.3285599	total: 884ms	remaining: 539ms
621:	learn: 0.3283772	total: 885ms	remaining: 538ms
622:	learn: 0.3282270	total: 886ms	remaining: 536ms
623:	learn: 0.3281514	total: 888ms	remaining: 535ms
624:	learn: 0.3279922	total: 889ms	remaining: 534ms
625:	learn: 0.3279458	total: 891ms	remaining: 532ms
626:	learn: 0.3278656	total: 892ms	remaining: 531ms
627:	learn: 0.3277472	total: 893ms	remaining: 529ms
628:	learn: 0.3277461	total: 894ms	remaining: 527ms
629:	learn: 0.3275535	total: 895ms	remaining: 526ms
630:	learn: 0.3273668	total: 896ms	remaining: 524ms
631:	learn: 0.3272803	total: 898ms	remaining: 523ms
632:	learn: 0.3271131	total: 899ms	remaining: 521ms
633:	learn: 0.3270469	total: 900ms	remaining: 520ms
634:	learn: 0.3268313	total: 902ms	remaining: 518ms
635:	learn: 0.3267130	total: 903ms	remaining: 517ms
636:	learn: 0.3266385	total: 904ms	remaining: 515ms
637:	learn: 0.3265307	total: 905ms	remaining: 514ms
638:	learn: 0.3264897	total: 907ms	remaining: 512ms
639:	learn: 0.3263355	total: 908ms	remaining: 511ms
640:	learn: 0.3262459	total: 909ms	remaining: 509ms
641:	learn: 0.3261430	total: 910ms	remaining: 508ms
642:	learn: 0.3260200	total: 912ms	remaining: 506ms
643:	learn: 0.3258796	total: 913ms	remaining: 505ms
644:	learn: 0.3258016	total: 914ms	remaining: 503ms
645:	learn: 0.3256181	total: 917ms	remaining: 502ms
646:	learn: 0.3254318	total: 919ms	remaining: 501ms
647:	learn: 0.3253734	total: 922ms	remaining: 501ms
648:	learn: 0.3252614	total: 923ms	remaining: 499ms
649:	learn: 0.3252516	total: 924ms	remaining: 498ms
650:	learn: 0.3250512	total: 926ms	remaining: 497ms
651:	learn: 0.3248282	total: 928ms	remaining: 495ms
652:	learn: 0.3247713	total: 930ms	remaining: 494ms
653:	learn: 0.3246464	total: 932ms	remaining: 493ms
654:	learn: 0.3245466	total: 933ms	remaining: 491ms
655:	learn: 0.3244453	total: 935ms	remaining: 490ms
656:	learn: 0.3243620	total: 936ms	remaining: 489ms
657:	learn: 0.3241670	total: 938ms	remaining: 488ms
658:	learn: 0.3240854	total: 940ms	remaining: 487ms
659:	learn: 0.3239966	total: 942ms	remaining: 485ms
660:	learn: 0.3239648	total: 945ms	remaining: 484ms
661:	learn: 0.3239035	total: 947ms	remaining: 484ms
662:	learn: 0.3238840	total: 948ms	remaining: 482ms
663:	learn: 0.3237669	total: 950ms	remaining: 480ms
664:	learn: 0.3237023	total: 951ms	remaining: 479ms
665:	learn: 0.3235218	total: 952ms	remaining: 477ms
666:	learn: 0.3234304	total: 953ms	remaining: 476ms
667:	learn: 0.3232495	total: 955ms	remaining: 474ms
668:	learn: 0.3231826	total: 956ms	remaining: 473ms

669:	learn: 0.3230517	total: 959ms	remaining: 472ms
670:	learn: 0.3229514	total: 961ms	remaining: 471ms
671:	learn: 0.3228010	total: 963ms	remaining: 470ms
672:	learn: 0.3224461	total: 964ms	remaining: 469ms
673:	learn: 0.3223529	total: 966ms	remaining: 467ms
674:	learn: 0.3221563	total: 968ms	remaining: 466ms
675:	learn: 0.3221332	total: 969ms	remaining: 465ms
676:	learn: 0.3220124	total: 971ms	remaining: 463ms
677:	learn: 0.3218706	total: 973ms	remaining: 462ms
678:	learn: 0.3215845	total: 975ms	remaining: 461ms
679:	learn: 0.3214355	total: 976ms	remaining: 459ms
680:	learn: 0.3212835	total: 979ms	remaining: 459ms
681:	learn: 0.3211619	total: 981ms	remaining: 457ms
682:	learn: 0.3210829	total: 982ms	remaining: 456ms
683:	learn: 0.3210682	total: 984ms	remaining: 455ms
684:	learn: 0.3209426	total: 985ms	remaining: 453ms
685:	learn: 0.3208008	total: 986ms	remaining: 452ms
686:	learn: 0.3207245	total: 988ms	remaining: 450ms
687:	learn: 0.3206900	total: 989ms	remaining: 449ms
688:	learn: 0.3206671	total: 990ms	remaining: 447ms
689:	learn: 0.3206028	total: 992ms	remaining: 446ms
690:	learn: 0.3205854	total: 993ms	remaining: 444ms
691:	learn: 0.3204779	total: 994ms	remaining: 443ms
692:	learn: 0.3203706	total: 996ms	remaining: 441ms
693:	learn: 0.3202434	total: 997ms	remaining: 440ms
694:	learn: 0.3200923	total: 998ms	remaining: 438ms
695:	learn: 0.3200174	total: 999ms	remaining: 437ms
696:	learn: 0.3198543	total: 1s	remaining: 435ms
697:	learn: 0.3198154	total: 1s	remaining: 434ms
698:	learn: 0.3197470	total: 1s	remaining: 432ms
699:	learn: 0.3195078	total: 1s	remaining: 431ms
700:	learn: 0.3193507	total: 1.01s	remaining: 429ms
701:	learn: 0.3192274	total: 1.01s	remaining: 428ms
702:	learn: 0.3191594	total: 1.01s	remaining: 426ms
703:	learn: 0.3190228	total: 1.01s	remaining: 425ms
704:	learn: 0.3189949	total: 1.01s	remaining: 423ms
705:	learn: 0.3189828	total: 1.01s	remaining: 422ms
706:	learn: 0.3189009	total: 1.01s	remaining: 420ms
707:	learn: 0.3187893	total: 1.01s	remaining: 419ms
708:	learn: 0.3185870	total: 1.02s	remaining: 417ms
709:	learn: 0.3185202	total: 1.02s	remaining: 416ms
710:	learn: 0.3183889	total: 1.02s	remaining: 414ms
711:	learn: 0.3181834	total: 1.02s	remaining: 413ms
712:	learn: 0.3180514	total: 1.02s	remaining: 411ms
713:	learn: 0.3178878	total: 1.02s	remaining: 410ms
714:	learn: 0.3178164	total: 1.02s	remaining: 408ms
715:	learn: 0.3176294	total: 1.02s	remaining: 407ms
716:	learn: 0.3174820	total: 1.03s	remaining: 405ms
717:	learn: 0.3174808	total: 1.03s	remaining: 403ms
718:	learn: 0.3174351	total: 1.03s	remaining: 402ms
719:	learn: 0.3173976	total: 1.03s	remaining: 400ms
720:	learn: 0.3172936	total: 1.03s	remaining: 399ms
721:	learn: 0.3171832	total: 1.03s	remaining: 397ms
722:	learn: 0.3171499	total: 1.03s	remaining: 396ms
723:	learn: 0.3169397	total: 1.03s	remaining: 394ms
724:	learn: 0.3168749	total: 1.03s	remaining: 393ms
725:	learn: 0.3168050	total: 1.04s	remaining: 391ms
726:	learn: 0.3167966	total: 1.04s	remaining: 390ms
727:	learn: 0.3166930	total: 1.04s	remaining: 388ms
728:	learn: 0.3165635	total: 1.04s	remaining: 387ms
729:	learn: 0.3164694	total: 1.04s	remaining: 385ms
730:	learn: 0.3163675	total: 1.04s	remaining: 384ms
731:	learn: 0.3162650	total: 1.04s	remaining: 382ms
732:	learn: 0.3161164	total: 1.04s	remaining: 381ms
733:	learn: 0.3159745	total: 1.05s	remaining: 379ms
734:	learn: 0.3158456	total: 1.05s	remaining: 378ms
735:	learn: 0.3156877	total: 1.05s	remaining: 376ms
736:	learn: 0.3156161	total: 1.05s	remaining: 375ms
737:	learn: 0.3155466	total: 1.05s	remaining: 373ms
738:	learn: 0.3153722	total: 1.05s	remaining: 372ms
739:	learn: 0.3151747	total: 1.05s	remaining: 371ms
740:	learn: 0.3150514	total: 1.05s	remaining: 369ms
741:	learn: 0.3150111	total: 1.06s	remaining: 368ms
742:	learn: 0.3148200	total: 1.06s	remaining: 366ms
743:	learn: 0.3146764	total: 1.06s	remaining: 365ms
744:	learn: 0.3143971	total: 1.06s	remaining: 363ms
745:	learn: 0.3143214	total: 1.06s	remaining: 362ms
746:	learn: 0.3142308	total: 1.06s	remaining: 361ms
747:	learn: 0.3140729	total: 1.07s	remaining: 359ms
748:	learn: 0.3138950	total: 1.07s	remaining: 358ms
749:	learn: 0.3137855	total: 1.07s	remaining: 357ms
750:	learn: 0.3137598	total: 1.07s	remaining: 355ms
751:	learn: 0.3136820	total: 1.07s	remaining: 354ms
752:	learn: 0.3135711	total: 1.07s	remaining: 353ms
753:	learn: 0.3134991	total: 1.08s	remaining: 351ms
754:	learn: 0.3134220	total: 1.08s	remaining: 350ms
755:	learn: 0.3133809	total: 1.08s	remaining: 348ms
756:	learn: 0.3133390	total: 1.08s	remaining: 347ms
757:	learn: 0.3132872	total: 1.08s	remaining: 345ms
758:	learn: 0.3132301	total: 1.08s	remaining: 344ms
759:	learn: 0.3130570	total: 1.08s	remaining: 342ms
760:	learn: 0.3129701	total: 1.08s	remaining: 341ms
761:	learn: 0.3129334	total: 1.09s	remaining: 339ms
762:	learn: 0.3127463	total: 1.09s	remaining: 338ms
763:	learn: 0.3125811	total: 1.09s	remaining: 336ms
764:	learn: 0.3124909	total: 1.09s	remaining: 335ms
765:	learn: 0.3123286	total: 1.09s	remaining: 334ms
766:	learn: 0.3121846	total: 1.09s	remaining: 332ms
767:	learn: 0.3120354	total: 1.09s	remaining: 331ms
768:	learn: 0.3119253	total: 1.09s	remaining: 329ms
769:	learn: 0.3118166	total: 1.1s	remaining: 328ms
770:	learn: 0.3117521	total: 1.1s	remaining: 326ms
771:	learn: 0.3116589	total: 1.1s	remaining: 325ms
772:	learn: 0.3116263	total: 1.1s	remaining: 323ms
773:	learn: 0.3114103	total: 1.1s	remaining: 322ms
774:	learn: 0.3112879	total: 1.1s	remaining: 320ms
775:	learn: 0.3112135	total: 1.1s	remaining: 319ms
776:	learn: 0.3111193	total: 1.1s	remaining: 317ms
777:	learn: 0.3110162	total: 1.11s	remaining: 316ms
778:	learn: 0.3109218	total: 1.11s	remaining: 314ms
779:	learn: 0.3108317	total: 1.11s	remaining: 313ms
780:	learn: 0.3107772	total: 1.11s	remaining: 312ms
781:	learn: 0.3106113	total: 1.11s	remaining: 310ms
782:	learn: 0.3104754	total: 1.11s	remaining: 309ms
783:	learn: 0.3102177	total: 1.11s	remaining: 307ms
784:	learn: 0.3100876	total: 1.12s	remaining: 306ms
785:	learn: 0.3100821	total: 1.12s	remaining: 305ms
786:	learn: 0.3099381	total: 1.12s	remaining: 303ms
787:	learn: 0.3098139	total: 1.12s	remaining: 302ms
788:	learn: 0.3097531	total: 1.12s	remaining: 301ms
789:	learn: 0.3095324	total: 1.13s	remaining: 299ms
790:	learn: 0.3094932	total: 1.13s	remaining: 298ms
791:	learn: 0.3093242	total: 1.13s	remaining: 296ms
792:	learn: 0.3092775	total: 1.13s	remaining: 295ms
793:	learn: 0.3092565	total: 1.13s	remaining: 294ms
794:	learn: 0.3091169	total: 1.13s	remaining: 292ms
795:	learn: 0.3088625	total: 1.13s	remaining: 291ms
796:	learn: 0.3087181	total: 1.14s	remaining: 289ms
797:	learn: 0.3086852	total: 1.14s	remaining: 288ms
798:	learn: 0.3086218	total: 1.14s	remaining: 286ms
799:	learn: 0.3084749	total: 1.14s	remaining: 285ms
800:	learn: 0.3083888	total: 1.14s	remaining: 284ms
801:	learn: 0.3083464	total: 1.14s	remaining: 282ms
802:	learn: 0.3083193	total: 1.14s	remaining: 281ms
803:	learn: 0.3081427	total: 1.15s	remaining: 279ms
804:	learn: 0.3080539	total: 1.15s	remaining: 278ms
805:	learn: 0.3079552	total: 1.15s	remaining: 276ms
806:	learn: 0.3076424	total: 1.15s	remaining: 275ms
807:	learn: 0.3075575	total: 1.15s	remaining: 273ms
808:	learn: 0.3075416	total: 1.15s	remaining: 272ms
809:	learn: 0.3074310	total: 1.15s	remaining: 270ms
810:	learn: 0.3073390	total: 1.15s	remaining: 269ms
811:	learn: 0.3071570	total: 1.16s	remaining: 268ms
812:	learn: 0.3069903	total: 1.16s	remaining: 266ms
813:	learn: 0.3068951	total: 1.16s	remaining: 265ms
814:	learn: 0.3068363	total: 1.16s	remaining: 263ms
815:	learn: 0.3065896	total: 1.16s	remaining: 262ms
816:	learn: 0.3065286	total: 1.16s	remaining: 260ms
817:	learn: 0.3063910	total: 1.16s	remaining: 259ms
818:	learn: 0.3063028	total: 1.16s	remaining: 257ms
819:	learn: 0.3062000	total: 1.17s	remaining: 256ms
820:	learn: 0.3061008	total: 1.17s	remaining: 255ms
821:	learn: 0.3060161	total: 1.17s	remaining: 253ms
822:	learn: 0.3057994	total: 1.17s	remaining: 252ms
823:	learn: 0.3057260	total: 1.17s	remaining: 250ms
824:	learn: 0.3056000	total: 1.17s	remaining: 249ms
825:	learn: 0.3054634	total: 1.17s	remaining: 247ms
826:	learn: 0.3053149	total: 1.18s	remaining: 246ms
827:	learn: 0.3052286	total: 1.18s	remaining: 244ms
828:	learn: 0.3051339	total: 1.18s	remaining: 243ms
829:	learn: 0.3050918	total: 1.18s	remaining: 241ms
830:	learn: 0.3049472	total: 1.18s	remaining: 240ms
831:	learn: 0.3048376	total: 1.18s	remaining: 239ms
832:	learn: 0.3047252	total: 1.18s	remaining: 237ms
833:	learn: 0.3046057	total: 1.19s	remaining: 236ms
834:	learn: 0.3045380	total: 1.19s	remaining: 234ms
835:	learn: 0.3044498	total: 1.19s	remaining: 233ms
836:	learn: 0.3043834	total: 1.19s	remaining: 232ms
837:	learn: 0.3043087	total: 1.19s	remaining: 230ms
838:	learn: 0.3040590	total: 1.19s	remaining: 229ms
839:	learn: 0.3040193	total: 1.19s	remaining: 227ms
840:	learn: 0.3038792	total: 1.19s	remaining: 226ms
841:	learn: 0.3037973	total: 1.2s	remaining: 224ms
842:	learn: 0.3037028	total: 1.2s	remaining: 223ms
843:	learn: 0.3035454	total: 1.2s	remaining: 221ms
844:	learn: 0.3035209	total: 1.2s	remaining: 220ms
845:	learn: 0.3034564	total: 1.2s	remaining: 219ms
846:	learn: 0.3033799	total: 1.2s	remaining: 217ms
847:	learn: 0.3032679	total: 1.2s	remaining: 216ms
848:	learn: 0.3031332	total: 1.2s	remaining: 214ms
849:	learn: 0.3030849	total: 1.21s	remaining: 213ms
850:	learn: 0.3030023	total: 1.21s	remaining: 211ms
851:	learn: 0.3028662	total: 1.21s	remaining: 210ms
852:	learn: 0.3027466	total: 1.21s	remaining: 209ms
853:	learn: 0.3026576	total: 1.21s	remaining: 207ms
854:	learn: 0.3024490	total: 1.21s	remaining: 206ms
855:	learn: 0.3023133	total: 1.21s	remaining: 204ms
856:	learn: 0.3022686	total: 1.22s	remaining: 203ms
857:	learn: 0.3021962	total: 1.22s	remaining: 201ms
858:	learn: 0.3019916	total: 1.22s	remaining: 200ms
859:	learn: 0.3019427	total: 1.22s	remaining: 198ms
860:	learn: 0.3017304	total: 1.22s	remaining: 197ms
861:	learn: 0.3016618	total: 1.22s	remaining: 196ms
862:	learn: 0.3015383	total: 1.22s	remaining: 194ms
863:	learn: 0.3014780	total: 1.22s	remaining: 193ms
864:	learn: 0.3014009	total: 1.23s	remaining: 191ms
865:	learn: 0.3013346	total: 1.23s	remaining: 190ms
866:	learn: 0.3012547	total: 1.23s	remaining: 188ms
867:	learn: 0.3011608	total: 1.23s	remaining: 187ms
868:	learn: 0.3010632	total: 1.23s	remaining: 186ms
869:	learn: 0.3009115	total: 1.23s	remaining: 184ms
870:	learn: 0.3008529	total: 1.23s	remaining: 183ms
871:	learn: 0.3008426	total: 1.23s	remaining: 181ms
872:	learn: 0.3007090	total: 1.24s	remaining: 180ms
873:	learn: 0.3005989	total: 1.24s	remaining: 178ms
874:	learn: 0.3005360	total: 1.24s	remaining: 177ms
875:	learn: 0.3004885	total: 1.24s	remaining: 176ms
876:	learn: 0.3004399	total: 1.24s	remaining: 174ms
877:	learn: 0.3003843	total: 1.24s	remaining: 173ms
878:	learn: 0.3003597	total: 1.24s	remaining: 171ms
879:	learn: 0.3002771	total: 1.25s	remaining: 170ms
880:	learn: 0.3001706	total: 1.25s	remaining: 168ms
881:	learn: 0.3000345	total: 1.25s	remaining: 167ms
882:	learn: 0.2998880	total: 1.25s	remaining: 166ms
883:	learn: 0.2997885	total: 1.25s	remaining: 164ms
884:	learn: 0.2996892	total: 1.25s	remaining: 163ms
885:	learn: 0.2995746	total: 1.25s	remaining: 161ms
886:	learn: 0.2994088	total: 1.25s	remaining: 160ms
887:	learn: 0.2993033	total: 1.26s	remaining: 158ms
888:	learn: 0.2992390	total: 1.26s	remaining: 157ms
889:	learn: 0.2991545	total: 1.26s	remaining: 156ms
890:	learn: 0.2989654	total: 1.26s	remaining: 154ms
891:	learn: 0.2988695	total: 1.26s	remaining: 153ms
892:	learn: 0.2987561	total: 1.26s	remaining: 151ms
893:	learn: 0.2987426	total: 1.26s	remaining: 150ms
894:	learn: 0.2986448	total: 1.26s	remaining: 148ms
895:	learn: 0.2984840	total: 1.27s	remaining: 147ms
896:	learn: 0.2984468	total: 1.27s	remaining: 146ms
897:	learn: 0.2983299	total: 1.27s	remaining: 144ms

898:	learn: 0.2982003	total: 1.27s	remaining: 143ms
899:	learn: 0.2981451	total: 1.27s	remaining: 141ms
900:	learn: 0.2980687	total: 1.27s	remaining: 140ms
901:	learn: 0.2979663	total: 1.28s	remaining: 139ms
902:	learn: 0.2979120	total: 1.28s	remaining: 137ms
903:	learn: 0.2978180	total: 1.28s	remaining: 136ms
904:	learn: 0.2976587	total: 1.28s	remaining: 134ms
905:	learn: 0.2975498	total: 1.28s	remaining: 133ms
906:	learn: 0.2975241	total: 1.28s	remaining: 132ms
907:	learn: 0.2973888	total: 1.28s	remaining: 130ms
908:	learn: 0.2972569	total: 1.29s	remaining: 129ms
909:	learn: 0.2972182	total: 1.29s	remaining: 127ms
910:	learn: 0.2971427	total: 1.29s	remaining: 126ms
911:	learn: 0.2969578	total: 1.29s	remaining: 125ms
912:	learn: 0.2969374	total: 1.29s	remaining: 123ms
913:	learn: 0.2969180	total: 1.29s	remaining: 122ms
914:	learn: 0.2968719	total: 1.29s	remaining: 120ms
915:	learn: 0.2967651	total: 1.3s	remaining: 119ms
916:	learn: 0.2966565	total: 1.3s	remaining: 118ms
917:	learn: 0.2964788	total: 1.3s	remaining: 116ms
918:	learn: 0.2961457	total: 1.3s	remaining: 115ms
919:	learn: 0.2960410	total: 1.3s	remaining: 113ms
920:	learn: 0.2958993	total: 1.3s	remaining: 112ms
921:	learn: 0.2957950	total: 1.3s	remaining: 110ms
922:	learn: 0.2957310	total: 1.31s	remaining: 109ms
923:	learn: 0.2954879	total: 1.31s	remaining: 108ms
924:	learn: 0.2954228	total: 1.31s	remaining: 106ms
925:	learn: 0.2953555	total: 1.31s	remaining: 105ms
926:	learn: 0.2951184	total: 1.31s	remaining: 103ms
927:	learn: 0.2949606	total: 1.31s	remaining: 102ms
928:	learn: 0.2948816	total: 1.31s	remaining: 101ms
929:	learn: 0.2947063	total: 1.32s	remaining: 99.1ms
930:	learn: 0.2945289	total: 1.32s	remaining: 97.7ms
931:	learn: 0.2943960	total: 1.32s	remaining: 96.3ms
932:	learn: 0.2943641	total: 1.32s	remaining: 94.9ms
933:	learn: 0.2941769	total: 1.32s	remaining: 93.4ms
934:	learn: 0.2941328	total: 1.32s	remaining: 92ms
935:	learn: 0.2940384	total: 1.32s	remaining: 90.6ms
936:	learn: 0.2939454	total: 1.32s	remaining: 89.2ms
937:	learn: 0.2938628	total: 1.33s	remaining: 87.7ms
938:	learn: 0.2937071	total: 1.33s	remaining: 86.3ms
939:	learn: 0.2935206	total: 1.33s	remaining: 84.9ms
940:	learn: 0.2934412	total: 1.33s	remaining: 83.5ms
941:	learn: 0.2933928	total: 1.33s	remaining: 82.1ms
942:	learn: 0.2931886	total: 1.33s	remaining: 80.6ms
943:	learn: 0.2929285	total: 1.33s	remaining: 79.2ms
944:	learn: 0.2928092	total: 1.34s	remaining: 77.8ms
945:	learn: 0.2926089	total: 1.34s	remaining: 76.4ms
946:	learn: 0.2924627	total: 1.34s	remaining: 74.9ms
947:	learn: 0.2924119	total: 1.34s	remaining: 73.5ms
948:	learn: 0.2922537	total: 1.34s	remaining: 72.1ms
949:	learn: 0.2921267	total: 1.34s	remaining: 70.7ms
950:	learn: 0.2920302	total: 1.34s	remaining: 69.3ms
951:	learn: 0.2919311	total: 1.34s	remaining: 67.8ms
952:	learn: 0.2918721	total: 1.35s	remaining: 66.4ms
953:	learn: 0.2917958	total: 1.35s	remaining: 65ms
954:	learn: 0.2915934	total: 1.35s	remaining: 63.6ms
955:	learn: 0.2915545	total: 1.35s	remaining: 62.2ms
956:	learn: 0.2915071	total: 1.35s	remaining: 60.7ms
957:	learn: 0.2913481	total: 1.35s	remaining: 59.3ms
958:	learn: 0.2912408	total: 1.35s	remaining: 57.9ms
959:	learn: 0.2911113	total: 1.36s	remaining: 56.5ms
960:	learn: 0.2910271	total: 1.36s	remaining: 55.1ms
961:	learn: 0.2909516	total: 1.36s	remaining: 53.7ms
962:	learn: 0.2909325	total: 1.36s	remaining: 52.3ms
963:	learn: 0.2909062	total: 1.36s	remaining: 50.8ms
964:	learn: 0.2907666	total: 1.36s	remaining: 49.4ms
965:	learn: 0.2906489	total: 1.36s	remaining: 48ms
966:	learn: 0.2905783	total: 1.36s	remaining: 46.6ms
967:	learn: 0.2905254	total: 1.37s	remaining: 45.2ms
968:	learn: 0.2904158	total: 1.37s	remaining: 43.8ms
969:	learn: 0.2903320	total: 1.37s	remaining: 42.4ms
970:	learn: 0.2902514	total: 1.37s	remaining: 40.9ms
971:	learn: 0.2902400	total: 1.37s	remaining: 39.5ms
972:	learn: 0.2901922	total: 1.37s	remaining: 38.1ms
973:	learn: 0.2901212	total: 1.37s	remaining: 36.7ms
974:	learn: 0.2900414	total: 1.38s	remaining: 35.3ms
975:	learn: 0.2899621	total: 1.38s	remaining: 33.9ms
976:	learn: 0.2898549	total: 1.38s	remaining: 32.5ms
977:	learn: 0.2898065	total: 1.38s	remaining: 31ms
978:	learn: 0.2897598	total: 1.38s	remaining: 29.6ms
979:	learn: 0.2895664	total: 1.38s	remaining: 28.2ms
980:	learn: 0.2895305	total: 1.38s	remaining: 26.8ms
981:	learn: 0.2894872	total: 1.38s	remaining: 25.4ms
982:	learn: 0.2893399	total: 1.39s	remaining: 24ms
983:	learn: 0.2893352	total: 1.39s	remaining: 22.6ms
984:	learn: 0.2893039	total: 1.39s	remaining: 21.1ms
985:	learn: 0.2892822	total: 1.39s	remaining: 19.7ms
986:	learn: 0.2891559	total: 1.39s	remaining: 18.3ms
987:	learn: 0.2890324	total: 1.39s	remaining: 16.9ms
988:	learn: 0.2889647	total: 1.39s	remaining: 15.5ms
989:	learn: 0.2889080	total: 1.4s	remaining: 14.1ms
990:	learn: 0.2887557	total: 1.4s	remaining: 12.7ms
991:	learn: 0.2885590	total: 1.4s	remaining: 11.3ms
992:	learn: 0.2884452	total: 1.4s	remaining: 9.87ms
993:	learn: 0.2884315	total: 1.4s	remaining: 8.46ms
994:	learn: 0.2883235	total: 1.4s	remaining: 7.05ms
995:	learn: 0.2881346	total: 1.4s	remaining: 5.64ms
996:	learn: 0.2880438	total: 1.41s	remaining: 4.23ms
997:	learn: 0.2879709	total: 1.41s	remaining: 2.82ms
998:	learn: 0.2879210	total: 1.41s	remaining: 1.41ms
999:	learn: 0.2878314	total: 1.41s	remaining: 0us

In [18]:
y_pred = model.predict(X_test)

In [19]:
model.score(X_test, y_test)

0.8659217877094972

In [20]:
from sklearn import metrics 
metrics.accuracy_score(y_test, y_pred)*100

86.59217877094973

In [21]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [22]:
test = test.drop(['Name', 'Ticket', 'Cabin'], axis=1)
test.head()

   PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0          892       3    male  34.5      0      0   7.8292        Q
1          893       3  female  47.0      1      0   7.0000        S
2          894       2    male  62.0      0      0   9.6875        Q
3          895       3    male  27.0      0      0   8.6625        S
4          896       3  female  22.0      1      1  12.2875        S

In [23]:
test.Sex[test.Sex == 'male'] = 1
test.Sex[test.Sex == 'female'] = 0
test.head()

C:\Users\Santanu Das\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Santanu Das\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

   PassengerId  Pclass Sex   Age  SibSp  Parch     Fare Embarked
0          892       3   1  34.5      0      0   7.8292        Q
1          893       3   0  47.0      1      0   7.0000        S
2          894       2   1  62.0      0      0   9.6875        Q
3          895       3   1  27.0      0      0   8.6625        S
4          896       3   0  22.0      1      1  12.2875        S

In [24]:
test = test.assign(Embarked=(test['Embarked'] == 'S').astype(int))
test.head()

   PassengerId  Pclass Sex   Age  SibSp  Parch     Fare  Embarked
0          892       3   1  34.5      0      0   7.8292         0
1          893       3   0  47.0      1      0   7.0000         1
2          894       2   1  62.0      0      0   9.6875         0
3          895       3   1  27.0      0      0   8.6625         1
4          896       3   0  22.0      1      1  12.2875         1

In [25]:
test = test.drop(['PassengerId'], axis=1)

In [26]:
test.head()

   Pclass Sex   Age  SibSp  Parch     Fare  Embarked
0       3   1  34.5      0      0   7.8292         0
1       3   0  47.0      1      0   7.0000         1
2       2   1  62.0      0      0   9.6875         0
3       3   1  27.0      0      0   8.6625         1
4       3   0  22.0      1      1  12.2875         1

In [27]:
test = test.fillna(test[['Age']].mean(axis = 0))
test.head()

   Pclass Sex   Age  SibSp  Parch     Fare  Embarked
0       3   1  34.5      0      0   7.8292         0
1       3   0  47.0      1      0   7.0000         1
2       2   1  62.0      0      0   9.6875         0
3       3   1  27.0      0      0   8.6625         1
4       3   0  22.0      1      1  12.2875         1

In [28]:
result = model.predict(test)

In [29]:
result.shape

(418,)

In [30]:
result = pd.DataFrame(result, columns=['Survived']).to_excel('Subm.xlsx')